"""Phase 6 — branch + commit + push, then open PR."""
from __future__ import annotations

import re
import time
import uuid

import structlog

from ..state import FixerState
from ..tools.azure_repos import AzureReposClient, AzureReposError
from ..tools.git_tools import (
    GitSafetyConfig,
    GitSafetyError,
    commit_all,
    create_branch,
    open_repo,
    push_branch,
)

logger = structlog.get_logger()


def _safety_cfg(fixer_cfg: dict) -> GitSafetyConfig:
    return GitSafetyConfig(
        branch_prefix=fixer_cfg.get("branch_prefix", "fix/sre-"),
        protected_branches=tuple(fixer_cfg.get("protected_branches", [])),
        forbid_force_push=bool(fixer_cfg.get("forbid_force_push", True)),
        forbid_branch_delete=bool(fixer_cfg.get("forbid_branch_delete", True)),
    )


def _slug(text: str, max_len: int = 32) -> str:
    s = re.sub(r"[^a-z0-9]+", "-", (text or "").lower()).strip("-")
    return (s or "fix")[:max_len]


async def branch_commit_node(state: FixerState, *, config: dict) -> dict:
    cfg = config["fixer"]
    safety = _safety_cfg(cfg)
    repo_path = state["repo_path"]
    plan = state.get("plan") or {}
    handoff = state.get("handoff") or {}
    issue = handoff.get("issue") or {}

    short = _slug(plan.get("summary") or issue.get("title") or "auto-fix")
    short_id = uuid.uuid4().hex[:6]
    branch = f"{safety.branch_prefix}{int(time.time())}-{short}-{short_id}"

    try:
        repo = open_repo(repo_path)
        create_branch(repo, branch, base=None, cfg=safety)
        msg = (
            f"fix(sre): {plan.get('summary') or issue.get('title') or 'auto-fix'}\n\n"
            f"Root cause:\n{plan.get('root_cause', '')}\n\n"
            f"Generated by SRE Fixer Agent."
        )
        sha = commit_all(repo, msg)
        if not sha:
            return {
                "status": "raised_human",
                "error": "No staged changes to commit (planner edits did not modify any tracked files).",
                "audit_trail": (state.get("audit_trail") or []) + [
                    {"step": "commit", "status": "empty", "branch": branch}
                ],
            }
        push_branch(repo, branch, cfg=safety)
    except GitSafetyError as e:
        logger.error("git_safety_blocked", err=str(e))
        return {
            "status": "raised_human",
            "error": f"Git safety policy blocked operation: {e}",
            "audit_trail": (state.get("audit_trail") or []) + [
                {"step": "branch_commit", "status": "blocked", "detail": str(e)}
            ],
        }
    except Exception as e:  # noqa: BLE001
        logger.exception("branch_commit_failed")
        return {
            "status": "raised_human",
            "error": f"Branch/commit/push failed: {e}",
            "audit_trail": (state.get("audit_trail") or []) + [
                {"step": "branch_commit", "status": "error", "detail": str(e)}
            ],
        }

    return {
        "branch_name": branch,
        "status": "branch_created",
        "audit_trail": (state.get("audit_trail") or []) + [
            {"step": "branch_commit", "status": "ok", "branch": branch, "sha": sha}
        ],
    }


async def open_pr_node(state: FixerState, *, config: dict) -> dict:
    cfg = config["fixer"]
    azure_cfg = cfg.get("azure_repos", {}) or {}
    repo_meta = state.get("azure_repo") or {}
    project = repo_meta.get("project")
    repository_id = repo_meta.get("repository_id")
    if not project or not repository_id:
        return {
            "status": "raised_human",
            "error": (
                "Azure Repos target not configured (need azure_repo.project and "
                "azure_repo.repository_id in the handoff or runtime state)."
            ),
            "audit_trail": (state.get("audit_trail") or []) + [
                {"step": "open_pr", "status": "missing_target"}
            ],
        }

    branch = state["branch_name"]
    plan = state.get("plan") or {}
    handoff = state.get("handoff") or {}
    issue = handoff.get("issue") or {}
    last_test = state.get("last_test") or {}

    try:
        client = AzureReposClient.from_env_and_repo(project=project, repository_id=repository_id)
    except AzureReposError as e:
        return {
            "status": "raised_human",
            "error": str(e),
            "audit_trail": (state.get("audit_trail") or []) + [
                {"step": "open_pr", "status": "no_credentials"}
            ],
        }

    title = f"[Auto-fix] {plan.get('summary') or issue.get('title') or 'SRE auto-fix'}"
    description = _build_pr_description(state, plan, last_test, handoff)
    target = repo_meta.get("target_branch") or azure_cfg.get("target_branch", "refs/heads/main")

    try:
        pr = client.create_pull_request(
            source_branch=branch,
            target_branch=target,
            title=title,
            description=description,
        )
    except AzureReposError as e:
        return {
            "status": "raised_human",
            "error": str(e),
            "audit_trail": (state.get("audit_trail") or []) + [
                {"step": "open_pr", "status": "error", "detail": str(e)}
            ],
        }

    logger.info("fixer_pr_opened", url=pr["url"], pr_id=pr["pr_id"], branch=branch)
    return {
        "pr": {"url": pr["url"], "pr_id": pr["pr_id"], "branch": branch},
        "status": "pr_opened",
        "audit_trail": (state.get("audit_trail") or []) + [
            {"step": "open_pr", "status": "ok", "url": pr["url"], "pr_id": pr["pr_id"]}
        ],
    }


async def raise_human_node(state: FixerState, *, config: dict) -> dict:
    """Terminal node: package everything for human review and stop."""
    logger.warning(
        "fixer_raised_human",
        attempt=state.get("attempt"),
        last_status=state.get("status"),
        error=state.get("error"),
    )
    return {
        "status": "raised_human",
        "audit_trail": (state.get("audit_trail") or []) + [
            {"step": "raise_human", "reason": state.get("error") or "policy"}
        ],
    }


def _build_pr_description(state: FixerState, plan: dict, last_test: dict, handoff: dict) -> str:
    issue = handoff.get("issue") or {}
    verdict = handoff.get("verdict") or {}
    edits = plan.get("edits") or []
    files_block = "\n".join(f"- `{e.get('relative_path')}`" for e in edits) or "(no files)"

    test_block = "(no tests run)"
    if last_test:
        cmd = " ".join(last_test.get("command") or [])
        test_block = (
            f"- Command: `{cmd}`\n"
            f"- Duration: {last_test.get('duration_ms', 0)}ms\n"
            f"- Result: **{'PASS' if last_test.get('passed') else 'FAIL'}**"
        )

    return (
        f"## Root cause\n{plan.get('root_cause', '')}\n\n"
        f"## Original issue\n"
        f"- Title: {issue.get('title', '(unknown)')}\n"
        f"- Reporter verdict: {verdict.get('classification', '?')} "
        f"(confidence {verdict.get('confidence', 0):.0%})\n\n"
        f"## Files changed\n{files_block}\n\n"
        f"## Tests\n{test_block}\n\n"
        f"{_verification_block(handoff)}"
        f"## Provenance\n"
        f"- SRE conversation/handoff for project_id `{state.get('project_id')}`\n"
        f"- Generated by: SRE Fixer Agent\n\n"
        f"> Human review required — do not auto-merge."
    )


def _verification_block(handoff: dict) -> str:
    """Verify-after-fix instructions (§9.17.4 v0.7).

    When the deployments adapter is off, verification can't auto-trigger — so the PR
    carries an explicit manual-trigger line. When even probes are unavailable, the repro
    test (§9.17.3) is named as the verification artifact of record.
    """
    conv_id = handoff.get("conversation_id") or handoff.get("conversation_link") or ""
    conv_ref = (str(conv_id).rsplit("/", 1)[-1]) if conv_id else ""
    deployments_enabled = bool(
        (((handoff.get("observability") or {}).get("deployments") or {}).get("enabled"))
    )
    repro = handoff.get("repro_test") or {}

    lines = ["## Verification\n"]
    if deployments_enabled:
        lines.append(
            "Deploy tracking is enabled — verification will auto-trigger when this fix "
            "reaches the test environment.\n"
        )
    else:
        if conv_ref:
            lines.append(
                "Deploy tracking unavailable — after this fix reaches the test environment, "
                f"trigger verification manually:\n\n`POST /agents/sre/verify-fix/{conv_ref}`\n"
            )
        else:
            lines.append(
                "Deploy tracking unavailable — trigger verification manually once this fix "
                "is deployed (`POST /agents/sre/verify-fix/{conversation_id}`).\n"
            )
    if repro.get("path") and repro.get("status") in {"red", "unverified"}:
        lines.append(
            f"A failing repro test (`{repro['path']}`) is included and is the verification "
            "artifact of record if live probes are unavailable.\n"
        )
    return "\n".join(lines) + "\n"
